# Generated by Django 3.2.5 on 2021-07-22 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('short_description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, default=None, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=50)),
                ('popover_text', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('html', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.DateField()),
                ('year_end', models.DateField(blank=True, default=None, null=True)),
                ('diploma_type', models.CharField(max_length=50)),
                ('diploma_description', models.CharField(max_length=50)),
                ('diploma_description_link', models.CharField(max_length=100)),
                ('entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.entity')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('UNDEFINED', '-'), ('Personal', (('ASC', 'Association'),)), ('Professional', (('CDD', 'FixedTerm contract'), ('CDI', 'Permanent contract'), ('INTERNSHIP', 'Internship'), ('APPRENTICE', 'Apprentice')))], max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('see_more_link', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.entity')),
            ],
        ),
        migrations.CreateModel(
            name='DiplomasAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('type', models.CharField(choices=[('UNDEFINED', '-'), ('DIPLOMA', 'Diploma'), ('AWARD', 'Award')], max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('see_more_link', models.CharField(max_length=100)),
                ('delivered_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.entity')),
                ('obtained_at_school', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.school')),
            ],
        ),
    ]
