# Generated by Django 3.2.5 on 2021-07-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiplomasAwards',
            new_name='DiplomaAward',
        ),
        migrations.RenameModel(
            old_name='SocialLinks',
            new_name='SocialLink',
        ),
    ]
