# Generated by Django 3.2.5 on 2021-07-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sociallink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='html',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
