# Generated by Django 3.2.5 on 2021-07-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_sociallink_html'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='popover_text',
            new_name='tooltip',
        ),
    ]
