# Generated by Django 3.2.5 on 2021-07-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_generalconfig_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalconfig',
            old_name='values',
            new_name='value',
        ),
    ]
