# Generated by Django 3.2.5 on 2021-07-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_values_generalconfig_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
