# Generated by Django 3.2.5 on 2021-07-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_entity_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='diploma_description',
            field=models.CharField(max_length=100),
        ),
    ]
