# Generated by Django 3.2.5 on 2021-07-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_experience_detailed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icons', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('UNDEFINED', '-'), ('Personal', (('ASC', 'Association'),)), ('Professional', (('CDD', 'Fixed term contract'), ('CDI', 'Permanent contract'), ('INTERNSHIP', 'Internship'), ('APPRENTICE', 'Apprenticeship')))], max_length=50),
        ),
    ]
