# Generated by Django 3.2.5 on 2021-07-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210723_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
