# Generated by Django 3.2.5 on 2021-07-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_interest_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('UNDEFINED', '-'), ('PERSONAL', 'Personal'), ('SCHOOL', 'School')], max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('github_url', models.CharField(max_length=200)),
                ('blog_url', models.CharField(max_length=200)),
                ('docs_url', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
    ]
