# Generated by Django 3.2.5 on 2021-07-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
