# Generated by Django 3.2.5 on 2021-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blog_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='docs_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
