# Generated by Django 3.2.5 on 2021-07-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210726_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='short_description',
        ),
        migrations.AddField(
            model_name='diplomaaward',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='diplomaaward',
            name='french_type',
            field=models.CharField(blank=True, choices=[('DIPLOMA', 'Diplome'), ('AWARD', 'Prix')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='french_type',
            field=models.CharField(blank=True, choices=[('Personal', (('ASC', 'Association'),)), ('Professional', (('CDD', 'CDD'), ('CDI', 'CDI'), ('INTERNSHIP', 'Stage'), ('APPRENTICE', 'Apprentisage')))], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='french_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='french_description',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Personel'), ('SCHOOL', 'Scolaire')], default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='french_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='french_diploma_description',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='french_diploma_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='diplomaaward',
            name='type',
            field=models.CharField(choices=[('DIPLOMA', 'Diploma'), ('AWARD', 'Award')], max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='type',
            field=models.CharField(choices=[('Personal', (('ASC', 'Association'),)), ('Professional', (('CDD', 'Fixed term contract'), ('CDI', 'Permanent contract'), ('INTERNSHIP', 'Internship'), ('APPRENTICE', 'Apprenticeship')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('SCHOOL', 'School')], max_length=50),
        ),
    ]
