# Generated by Django 3.2.5 on 2021-07-26 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210726_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='french_type',
        ),
    ]
