# Generated by Django 3.2.5 on 2021-07-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_project_french_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaaward',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='french_description',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Personel'), ('SCHOOL', 'Scolaire')], default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='french_diploma_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
