# Generated by Django 3.2.5 on 2021-07-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20210726_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
