# Generated by Django 3.2.5 on 2021-07-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_project_french_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomaaward',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='see_more_link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='generalconfig',
            name='value',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='interest',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='interest',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='icons',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='french_description',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='french_diploma_description',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='html',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
